package com.siprell.plugin.gradle.bootstrap

import org.gradle.api.DefaultTask
import org.gradle.api.file.FileTree
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskExecutionException

class BootstrapGradlePlugin implements Plugin<Project> {
	final BOOTSTRAP_DEFAULT_VERSION = "3.3.5"
	final FA_DEFAULT_VERSION = "4.3.0"

	void apply(Project project) {

		// Shared properties
		def downloadZipFile = new DownloadZipFile()
		String tmpDir = "${project.buildDir}/tmp"
		def properties = project.hasProperty("bootstrapFramework") ? project.bootstrapFramework : [:]
		// Bootstrap Framework properties
		String bootstrapVersion = properties.version ?: BOOTSTRAP_DEFAULT_VERSION
		boolean useIndividualJs = properties.useIndividualJs ?: false
		boolean useLess = properties.useLess ?: false
		String jsPath = properties.jsPath ? properties.jsPath : "grails-app/assets/javascripts"
		String cssPath = properties.cssPath ? properties.cssPath : "grails-app/assets/stylesheets"
		boolean useAssetPipeline = jsPath.contains("assets")
		FileTree bootstrapZipTree
		// FontAwesome properties
		def fontAwesome = properties.fontAwesome
		boolean useFontAwesome = properties.fontAwesome ? true : false
		String fontAwesomeVersion = fontAwesome?.version ?: FA_DEFAULT_VERSION
		boolean fontAwesomeUseLess = fontAwesome?.useLess ?: false
		FileTree fontAwesomeZipTree

		project.afterEvaluate {
		    // TODO fix this mess
			project.tasks.createBootstrapJs.mustRunAfter project.tasks.downloadBootstrapZip
			project.tasks.createBootstrapFonts.mustRunAfter project.tasks.downloadBootstrapZip
			project.tasks.createBootstrapCssIndividual.mustRunAfter project.tasks.downloadBootstrapZip
			project.tasks.createBootstrapLess.mustRunAfter project.tasks.downloadBootstrapZip
			project.tasks.createBootstrapMixins.mustRunAfter project.tasks.downloadBootstrapZip

			project.tasks.processResources.dependsOn(
				"downloadBootstrapZip",
				"createBootstrapJsAll",
				"createBootstrapJs",
				"createBootstrapCssAll",
				"createBootstrapFonts",
				"createBootstrapCssIndividual",
				"createBootstrapLessAll",
				"createBootstrapLess",
				"createBootstrapMixins"
			)
		}


		project.task("bootstrapFrameworkVersions") << {
			println "$BOOTSTRAP_DEFAULT_VERSION is the default Bootstrap Framework version."
			println "$FA_DEFAULT_VERSION is the default FontAwesome version."
		}

		project.task("downloadBootstrapZip") {
			String description = "Bootstrap Framework"
			String filePrefix = "bootstrap-v"
			String url = "https://github.com/twbs/bootstrap/archive/v${bootstrapVersion}.zip"
			String zipFilename = "${filePrefix}${bootstrapVersion}.zip"

			def zipFile = downloadZipFile.download(tmpDir, description, filePrefix, url, bootstrapVersion, zipFilename)
			bootstrapZipTree = (zipFile instanceof File) ? project.zipTree(zipFile) : null
		}

		project.task("downloadFontAwesomeZip") {
		    if (useFontAwesome) {
    			String description = "FontAwesome"
	    		String filePrefix = "fontAwesome-v"
	    		String url = "http://fontawesome.io/assets/font-awesome-${version}.zip"
	    		String zipFilename = "${filePrefix}${fontAwesomeVersion}.zip"
		        
    			def zipFile = downloadZipFile.download(tmpDir, description, filePrefix, url, fontAwesomeVersion, zipFilename)
    			fontAwesomeZipTree = (zipFile instanceof File) ? project.zipTree(zipFile) : null
		    }
		}

		project.task("createBootstrapJsAll") {
			def path = "${project.projectDir}/$jsPath"
			def file = "bootstrap-all.js"
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file file
				outputs.dir path
			}
			doLast {
				if (useAssetPipeline) {
					def bootstrapJs = project.file("$path/$file")
					bootstrapJs.text = """//
// Do not edit this file. It will be overwritten by the bootstrap plugin.
//
//= require bootstrap/bootstrap.js
"""
				}
			}
		}

		project.task("createBootstrapJs") {
			def path = "${project.projectDir}/$jsPath/bootstrap"
			if (!project.file(path).exists()) {
				project.mkdir(path)
			}
			def files = bootstrapZipTree.matching {
				include "*/dist/js/bootstrap.js"
				if (useIndividualJs) {
					include "*/js/*.js"
				}
			}.collect()
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file files
				outputs.dir path
			}
			doLast {
				project.copy {
					from files
					into path
				}
				if (!useIndividualJs) {
					project.file(path).listFiles().each { file ->
						if (file.name != "bootstrap.js") {
							file.delete()
						}
					}
				}
			}
		}

		project.task("createBootstrapCssAll") {
			def path = "${project.projectDir}/$cssPath"
			def file = "bootstrap-all.css"
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file file
				outputs.dir path
			}
			doLast {
				if (useAssetPipeline) {
					def bootstrapCss = project.file("$path/$file")
					bootstrapCss.text = """/*
* Do not edit this file. It will be overwritten by the bootstrap plugin.
*
*= require bootstrap/css/bootstrap.css
*= require bootstrap/css/bootstrap-theme.css
*/
"""
				}
			}
		}

		project.task("createBootstrapFonts") {
			def path = "${project.projectDir}/$cssPath/bootstrap/fonts"
			if (!project.file(path).exists()) {
				project.mkdir(path)
			}
			def files = bootstrapZipTree.matching {
				include "*/fonts/*"
			}.collect()
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file files
				outputs.dir path
			}
			doLast {
				project.copy {
					from files
					into path
				}
			}
		}

		project.task("createBootstrapCssIndividual") {
			def path = "${project.projectDir}/$cssPath/bootstrap/css"
			if (!project.file(path).exists()) {
				project.mkdir(path)
			}
			def files = bootstrapZipTree.matching {
				include "*/dist/css/*.css"
				exclude "*/dist/css/*.min.css"
			}.collect()
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file files
				outputs.dir path
			}
			doLast {
				project.copy {
					from files
					into path
				}
			}
		}

		project.task("createBootstrapLessAll") {
			def path = "${project.projectDir}/$cssPath"
			def file = "bootstrap-less.less"
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file file
				outputs.dir path
			}
			doLast {
				if (useLess && useAssetPipeline) {
					def bootstrapLess = project.file("$path/$file")
					bootstrapLess.text = """/*
* This file is for your less and mixin customizations.
* It was created by the bootstrap plugin.
* It will not be overwritten.
*
* You can import all less and mixin files as shown below,
* or you can import them individually.
* See https://github.com/kensiprell/grails3-bootstrap/blob/master/README.md#less
*/

@import "bootstrap/less/bootstrap.less";

/*
* Your customizations go below this section.
*/
"""
				}
			}
		}

		project.task("createBootstrapLess") {
			def path = "${project.projectDir}/$cssPath/bootstrap/less"
			def files = bootstrapZipTree.matching {
				include "*/less/*.less"
			}.collect()
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file files
				outputs.dir path
			}
			doLast {
				if (useLess) {
					project.copy {
						from files
						into path
					}
				} else {
					project.file(path).deleteDir()
				}
			}
		}

		project.task("createBootstrapMixins") {
			def path = "${project.projectDir}/$cssPath/bootstrap/less/mixins"
			if (useLess && !project.file(path).exists()) {
				project.mkdir(path)
			}
			def files = bootstrapZipTree.matching {
				include "*/less/mixins/*.less"
			}.collect()
			project.gradle.taskGraph.whenReady { graph ->
				inputs.file files
				outputs.dir path
			}
			doLast {
				if (useLess) {
					project.copy {
						from files
						into path
					}
				} else {
					project.file(path).deleteDir()
				}
			}
		}
	}
}

class DownloadZipFile { 
	String fileSuffix = ".zip"

	def download(String tmp, String description, String filePrefix, String url, String version, String zipFilename) {
	    println "TEST START"
	    println "TEST tmp: $tmp" 
	    println "TEST description: $description"
	    println "TEST filePrefix: $filePrefix"
	    println "TEST url: $url"
	    println "TEST version: $version"
	    println "TEST zipFilename: $zipFilename"
	    println "TEST END"
		def tmpDir = new File("$tmp")
		if (!tmpDir.exists()) {
			tmpDir.mkdir()
		}
    	def zipFile = new File("$tmp/$zipFilename")
    	if (zipFile.exists()) {
    	    return zipFile
    	}
		try {
		    def file = zipFile.newOutputStream()
			file  << new URL(url).openStream()
			file.close()
			return zipFile
		} catch (e) {
		    zipFile.delete()
			println "Error: Could not download $url.\n$version is an invalid $description version, or you are not connected to the Internet."
			List<File> zipFiles = []
			tmpDir.listFiles().each {
				if (it.name.startsWith(filePrefix)) {
					zipFiles << it
				}
			}
			if (zipFiles.size() > 0) {
				File zipFileOld
				if (zipFiles.size() == 1) {
					zipFileOld = zipFiles[0]
				} else {
					zipFileOld = zipFiles.sort(false) { a, b ->
						def tokens = [a.name.minus(filePrefix).minus(fileSuffix), b.name.minus(filePrefix).minus(fileSuffix)]
						tokens*.tokenize('.')*.collect { it as int }.with { u, v ->
							[u, v].transpose().findResult { x, y -> x <=> y ?: null } ?: u.size() <=> v.size()
						}
					}[-1]
				}
				String newVersion = zipFileOld.name.minus(filePrefix).minus(fileSuffix)
				println "Using $description version $newVersion instead of $version."
				return zipFileOld
			} else {
			    // TODO stop tasks execution?
				println "FATAL ERROR: No $description zip files found in $tmpDir."
			}
		}
	}
}

